- cgi-bin/server.py
This is a minor change to `cgi-bin/server.py` to allow the standalone debug server to be run with a port defined alongside the host name address. Example usage: `python cgi-bin/server.py 127.0.0.1 31337` to run the standalone server on 127.0.0.1:31337
> Debug server: Use port if provided

- supysonic/api/__init__.py
- supysonic/api/albums_songs.py
- supysonic/api/annotation.py
- supysonic/api/browse.py
- supysonic/api/chat.py
- supysonic/api/media.py
- supysonic/api/playlists.py
- supysonic/api/search.py
- supysonic/api/user.py
The subsonic API docs do not generally specify whether the GET or POST method should be used. Indeed, `py-sonic` (<a href="https://pypi.python.org/pypi/py-sonic/">pypi</a>, <a href="https://github.com/crustymonkey/py-sonic">git</a>, note that `py-sonic` only supports token-based authentication currently; crustymonkey/py-sonic#17 is a request to add a fallback option to use old auth), which is used, for example, by <a href="https://pypi.python.org/pypi/Mopidy-Subsonic">`mopidy-subsonic`</a> uses POST requests for most of its actions.
This pull makes `supysonic` accept both GET and POST requests in the API.
> Support POST requests for API

- supysonic/scanner.py
This enables supysonic to remove unused albums (and therefore artists) when the metadata of an existing track is modified and there are no longer any more tracks tagged with the album.
> Rescan albums when track metadata changes

- supysonic/api/media.py
This pull adds the ability to use range requests in `send_file` when streaming or downloading original files; see https://github.com/pallets/flask/blob/3fc8be5a4e9c1db58dcc74d3d48bf70b6a8db932/flask/helpers.py#L586.
Once werkzeug v0.12 is released, with G-d's help, this will start supporting range requests.
See also <a href="https://github.com/pallets/werkzeug/blob/master/CHANGES">werkzeug changelog</a>.
> use range requests when available

- supysonic/web.py
`makedirs` is imported directly and must be used without `os`
> Fix small issue with makedirs import

- supysonic/api/playlists.py
This allows public playlist contents to be accessed  even when not an admin. Previously they would show up in the list of playlists, but would not allow access to the playlist itself.
Thanks for the wonderful project! :-)
> Allow accessing public playlists via API when not admin

- supysonic/managers/folder.py
Expand the path using the system environment
before generating the absolute path.
For example, ~ was not being expanded to
the user's home directory.
> Expand path when adding a folder

- supysonic/api/errors.py
This prevents a `TypeError` from being raised when attempting to serialize an `Exception` to a JSON object.
Note that this doesn't fix the root cause of the issue (which I haven't been able to track down yet). However, if a `SubsonicAPIException` is raised with the an `Exception` object being set as the `message`, the logical thing to do is to stringify that message before returning it to the client (even though it probably shouldn't ever happen). At least then the client will have some record of what went wrong.
Exception for reference:
```
Exception on /rest/getCoverArt.view [GET]
Traceback (most recent call last):
File "/home/supysonic/venv/lib/python3.6/site-packages/flask/app.py", line 1982, in wsgi_app
response = self.full_dispatch_request()
File …
```
> Ensure that Exceptions are stringified before being returned

- supysonic/api/media.py
Asking nicely with a SIGTERM doesn't cause the transcoding process(es)
to exit. Using SIGKILL gets the job done.
This was verified by manually sending SIGTERM and SIGKILL signals to
hung transcoding processes, as well as getting a client to abort stream
requests before they had completed.
Fixes #55
> Kill transcoding processes on error

- supysonic/api/media.py
- supysonic/lastfm.py
Currently, if a remote api like chartlyrics or last.fm is not responding, supysonic will hang for a pretty long time, and will leave the client hanging for longer.  Adding a timeout ensures that this error is quickly reported and handled.
As of me posting this, chartlyrics.com is currently down, hence why tests are failing.  This doesn't fix that, but it at least makes the problem a little more obvious and moves on with the tests, and allows production servers to respond healthily to the missing api.
> Add a timeout when fetching remote resources

- config.sample
- setup.py
- supysonic/api/media.py
- supysonic/cache.py
- supysonic/config.py
- supysonic/py23.py
- supysonic/web.py
- tests/base/__init__.py
- tests/base/test_cache.py
~This code currently works, but is not ready to merge. Check commit messages for implementation details while it's in a WIP state.~ See below.
@spl0k: Before I dig too deep into this, do you have any general thoughts on how you would like to see something like this implemented?
---------------------------------
Quick summary
-------------
- Adds a Cache class (plus tests for it) that provides an API for managing a cache of files on disk
- Adds two new settings to the configuration file: `cache_size` (default 512MB) and `transcode_cache_size` (default 1GB).
- Creates two cache managers using the settings above: one for general stuff (currently album art and lyrics) and one for transcodes
- Adds the caching of transcoded files to disk for future use
- Modifies the existing image caching to …
> Implement a cache manager for transcodes and other files

- setup.py
- supysonic/py23.py
- supysonic/scanner.py
- tests/base/test_scanner.py
While trying to run the test suite with python3, it kept crashing because `scandir` is missing. `scandir` is a python2 only dependency (since it's been merged in `os` in python3) so this PR marks it as so in `setup.py`.
```
running test
Searching for scandir<2.0.0
Note: Bypassing https://pypi.org/simple/scandir/ (disallowed host; see http://bit.ly/2hrImnY for details).
Couldn't find index page for 'scandir' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Note: Bypassing https://pypi.org/simple/ (disallowed host; see http://bit.ly/2hrImnY for details).
No local packages or working download links found for scandir<2.0.0
error: Could not find suitable distribution for Requirement.parse('scandir<2.0.0')
E: pybuild pybuild:341: test: plugin distutils failed with: …
```
> don't require scandir for python3

- supysonic/templates/layout.html
Hello!
This PR removes support for IE8 and IE9. That code was causing me problems for the Debian packaging, since respond.js isn't packaged in Debian and I can't add embedded copies of external libraries.
It's not critical (I could patch that code out in Debian), but I feel it's OK to deprecate IE8 an IE9 support. IE9 supports `@media` calls and IE10 supports HTML5, so from IE10 or greater the current code is fine.
> remove support for IE8-9

- supysonic/cli.py
Without the patch:
```
foo@bar:/home/foo# supysonic-cli folder scan Musique
Couldn't connect to the daemon, scanning in foreground
Scanning 'Musique': 11407 files scannedScanning done
Added: 0 artists, 0 albums, 0 tracks
Deleted: 0 artists, 0 albums, 0 tracks
```
With the patch:
```
foo@bar:/home/foo# supysonic-cli folder scan Musique
Couldn't connect to the daemon, scanning in foreground
Scanning 'Musique': 11453 files scanned
Scanning done
Added: 0 artists, 0 albums, 0 tracks
Deleted: 0 artists, 0 albums, 0 tracks
```
> Make sure all messages are printed on a new line

- docs/transcoding.md
- supysonic/api/media.py
Add a `default_transcode_target` option to the `transcoding` section of the config.
The value of this option will be used as target format when a client requests a bitrate lower than the original file with no target format.
I found that DSub was eating my mobile data when streaming flac files, even though it is configured to limit bitrate to 256k on mobile. Turns out that in this configuration, DSub only requests a bitrate without any target format. As a result, the whole flac file was returned.
> Add default_transcode_target option

- README.md
- config.sample
- docs/transcoding.md
- supysonic/api/media.py
I didn't change the transcode settings in `config.sample` to ones that add metadata but can if you think that adding the metadata is a reasonable default.
Other small fixes:
- Fixed typo in README
- Fixed `oggenc2` using `-q` instead of `-Q` to mean "quiet"
Fixes #170
> Support setting basic metadata in transcoded media

- supysonic/api/formatters.py
Fix two minor `SyntaxWarning` uncovered by running the testsuite with python3.8 
```
/builds/python-team/applications/supysonic/debian/output/supysonic-0.4.1/supysonic/api/formatters.py:63: SyntaxWarning: "is" with a literal. Did you mean "=="?
rv = {"status": "failed" if elem is "error" else "ok", "version": API_VERSION}
/builds/python-team/applications/supysonic/debian/output/supysonic-0.4.1/supysonic/api/formatters.py:139: SyntaxWarning: "is" with a literal. Did you mean "=="?
"status": "failed" if elem is "error" else "ok",
```
> fix SyntaxWarnings

- supysonic/api/__init__.py
- supysonic/api/media.py
- supysonic/cache.py
- supysonic/jukebox.py
- supysonic/schema/migration/postgres/20180317.py
- supysonic/schema/migration/sqlite/20180317.py
Bare excepts will catch `GeneratorExit` exceptions which are raised whenever a generator stops. This was causing issues when transcoding and caching the results.
All instances of bare excepts have been replaced with scoped versions.
> Fix exception handling

- supysonic/db.py
- tests/__init__.py
- tests/issue221.py
This PR merges duplicate track genre tags when constructing the album genre info. This change will help players which display the album genre to avoid cluttering their display with a repeated list of identical genre names. This idea came from https://github.com/peguerosdc/subplayer/issues/48
> merge identical genre tags in album info

- docs/setup/install.rst
Since Debian 11 (Bullseye), python2 has been deprecated and all python
packages should now use python3-foo versions.
> Fix wrong package name for apt install commands.

- docs/conf.py
- docs/man/README.md
- docs/man/supysonic-cli-folder.rst
- docs/man/supysonic-cli-user.rst
- docs/man/supysonic-cli.rst
- docs/man/supysonic-daemon.rst
- docs/man/supysonic-server.rst
Closes #225.
I tried to be as consistent as possible and favor a cleaner `man` output over a cleaner `html` output (although I think the HTML pages look good nonetheless).
For manpages with arguments, arguments are in bold and options in italic (`supysonic-cli*`). When there's no arguments, the options are in bold (`supysonic-server`).
I made some choices based on opinions about style and things and as such, I'd be happy to make modifications if you disagree :)
You can build the man pages by using:
PYTHONPATH=. sphinx-build -b man docs/ foobar
Then can then be read by running:
man ./foobar/supysonic-cli.1
> Modify the man pages for sphinx.

- supysonic/db.py
- supysonic/scanner.py
- supysonic/schema/migration/mysql/20230331.sql
- supysonic/schema/migration/postgres/20230331.sql
- supysonic/schema/migration/sqlite/20230331.sql
- tests/base/test_scanner.py
In 0183bcb6 the scanner switched from using Mutagen to Mediafile for scanning files. Prior to this commit, the bitrate from Mutagen was divided by 1000 to convert it from bps to kbps. After switching to Mediafile, the conversion was dropped even though Mediafile also reports bitrate in bps.
This PR adds back the conversion to kbps, adds a test that checks that the bitrate and some other metadata is correct, as well as a database migration that should fix up any existing errors.
The database migration will find all tracks that don't end with `.wav` (case-insensitive) and have a bitrate > 16000 and divide their bitrate by 1000. I have tested the migration using sqlite, but **have not tested it with postgres or mysql**.
Fixing this issue will also fix transcoding being applied in some cases …
> Fix bitrate units when scanning and add a DB migration to fix existing tracks

- setup.py
In Python 3.10 and 3.11, distutils has been formally marked as deprecated. Code that imports distutils will no longer work from Python 3.12.
I'm pretty sure distutils.dir_util.remove_tree() and shutil.rmtree() do the same exact same thing and this should fix the issue :)
> Replace distutils.dir_util.remove_tree() by shutil.rmtree().

- supysonic/db.py
- tests/base/test_db.py
This fixes decimal places appearing in track durations. Currently this is only shown in the playlists UI:
| Before | After |
| -| -- |
| ![before](https://github.com/user-attachments/assets/2e7e1ee1-8982-43b0-8810-f42c11c73a52) | ![after](https://github.com/user-attachments/assets/52920d4c-e5ba-48e0-8d1d-ae58af465aa7) |
Also added some very basic tests to check durations around the hour boundary are properly handled.
> Fix track duration display

- supysonic/frontend/user.py
As mentioned in #267 it is not possible to change the email address in any way, neither of your own user nor, being admin, of any other user.
This happens simply because the change is not saved in the function that handles the `POST` in `changemail`.
> Fixes changemail POST

- supysonic/templates/profile.html
This small change fixes a bug that snuck up on me and causes the two Link and Unlink buttons to appear in the LastFM status.
> Fixes LastFM link and unlink buttons
